const foods = [
    {
      "id": "5fc19e0996f8c332407d68e9",
      "title": "Honey Soy Salmon",
      "category": "lunch",
      "picture": "https://i.ibb.co/YQmT407/lunch6.png",
      "shortDecription": "How we dream about our future",
      "details": "Toothsome, strictly used, refers to edible and pleasant food, or you could even write tasty, appetizing or delicious instead, something really pleasant to the sense of taste. But you will see it very often meaning healthy food, good tasting food that has something more than good taste going for it.",
      "price": 10,
      "name": "Beryl Leon",
      "company": "ZENSOR",
      "email": "berylleon@zensor.com",
      "phone": "+1 (940) 501-3288"
    },
    {
      "id": "5fc19e09a3b855a53ea5b0f3",
      "title": "Indian Lunch",
      "category": "lunch",
      "picture": "https://i.ibb.co/CMhh2s7/lunch4.png",
      "shortDecription": "How we dream about our future",
      "details": "Toothsome, strictly used, refers to edible and pleasant food, or you could even write tasty, appetizing or delicious instead, something really pleasant to the sense of taste. But you will see it very often meaning healthy food, good tasting food that has something more than good taste going for it.",
      "price": 18,
      "name": "Kirk Mann",
      "company": "VIAGRAND",
      "email": "kirkmann@viagrand.com",
      "phone": "+1 (978) 536-2206"
    },
    {
      "id": "5fc19e095d2c2847645d1e5d",
      "title": "Beaf Steak",
      "category": "lunch",
      "picture": "https://i.ibb.co/S6wmBVw/lunch5.png",
      "shortDecription": "How we dream about our future",
      "details": "Toothsome, strictly used, refers to edible and pleasant food, or you could even write tasty, appetizing or delicious instead, something really pleasant to the sense of taste. But you will see it very often meaning healthy food, good tasting food that has something more than good taste going for it.",
      "price": 20,
      "name": "Ashley Rhodes",
      "company": "FANFARE",
      "email": "ashleyrhodes@fanfare.com",
      "phone": "+1 (943) 453-2369"
    },
    {
      "id": "5fc19e09a8be0e156a5a85f8",
      "title": "Healthy Meal Plan",
      "category": "lunch",
      "picture": "https://i.ibb.co/LhbGJ2D/lunch1.png",
      "shortDecription": "How we dream about our future",
      "details": "Toothsome, strictly used, refers to edible and pleasant food, or you could even write tasty, appetizing or delicious instead, something really pleasant to the sense of taste. But you will see it very often meaning healthy food, good tasting food that has something more than good taste going for it.",
      "price": 16,
      "name": "Jerri Reid",
      "company": "NEUROCELL",
      "email": "jerrireid@neurocell.com",
      "phone": "+1 (925) 436-3874"
    },
    {
      "id": "5fc19e097aa2823743457271",
      "title": "Trragon-Rubbed-Salmon",
      "category": "lunch",
      "picture": "https://i.ibb.co/v4h2Wsk/lunch3.png",
      "shortDecription": "How we dream about our future",
      "details": "Toothsome, strictly used, refers to edible and pleasant food, or you could even write tasty, appetizing or delicious instead, something really pleasant to the sense of taste. But you will see it very often meaning healthy food, good tasting food that has something more than good taste going for it.",
      "price": 15,
      "name": "Mathews Wagner",
      "company": "BALUBA",
      "email": "mathewswagner@baluba.com",
      "phone": "+1 (919) 410-3523"
    },
    {
      "id": "5fc19e09adab10d97250684b",
      "title": "Fried Chicken Bento",
      "category": "lunch",
      "picture": "https://i.ibb.co/y8GwTH9/lunch2.png",
      "shortDecription": "How we dream about our future",
      "details": "Toothsome, strictly used, refers to edible and pleasant food, or you could even write tasty, appetizing or delicious instead, something really pleasant to the sense of taste. But you will see it very often meaning healthy food, good tasting food that has something more than good taste going for it.",
      "price": 17,
      "name": "Concetta Schmidt",
      "company": "MULTIFLEX",
      "email": "concettaschmidt@multiflex.com",
      "phone": "+1 (829) 490-3572"
    },
    {
        "id": "5fc19eb119a36cd950a014b4",
        "title": "Eggs benedict",
        "category": "breakfast",
        "picture": "https://i.ibb.co/FbBxM0C/breakfast1.png",
        "shortDecription": "How we dream about our future",
        "details": "Toothsome, strictly used, refers to edible and pleasant food, or you could even write tasty, appetizing or delicious instead, something really pleasant to the sense of taste. But you will see it very often meaning healthy food, good tasting food that has something more than good taste going for it.",
        "price": 13,
        "name": "Johanna Leach",
        "company": "BARKARAMA",
        "email": "johannaleach@barkarama.com",
        "phone": "+1 (903) 512-3393"
      },
      {
        "id": "5fc19eb1f03a1196af305c31",
        "title": "Bagel and cream cheese",
        "category": "breakfast",
        "picture": "https://i.ibb.co/3BnKD64/breakfast2.png",
        "shortDecription": "How we dream about our future",
        "details": "Toothsome, strictly used, refers to edible and pleasant food, or you could even write tasty, appetizing or delicious instead, something really pleasant to the sense of taste. But you will see it very often meaning healthy food, good tasting food that has something more than good taste going for it.",
        "price": 11,
        "name": "Marlene Kemp",
        "company": "ROOFORIA",
        "email": "marlenekemp@rooforia.com",
        "phone": "+1 (939) 571-3342"
      },
      {
        "id": "5fc19eb1dc5226665f61c7ff",
        "title": "Full breakfast egg toast",
        "category": "breakfast",
        "picture": "https://i.ibb.co/zZHLHY0/breakfast3.png",
        "shortDecription": "How we dream about our future",
        "details": "Toothsome, strictly used, refers to edible and pleasant food, or you could even write tasty, appetizing or delicious instead, something really pleasant to the sense of taste. But you will see it very often meaning healthy food, good tasting food that has something more than good taste going for it.",
        "price": 11,
        "name": "Dale Casey",
        "company": "CRUSTATIA",
        "email": "dalecasey@crustatia.com",
        "phone": "+1 (915) 580-2684"
      },
      {
        "id": "5fc19eb1662e05cd02df9596",
        "title": "Toast fried Egg Butter",
        "category": "breakfast",
        "picture": "https://i.ibb.co/X863yb3/breakfast4.png",
        "shortDecription": "How we dream about our future",
        "details": "Toothsome, strictly used, refers to edible and pleasant food, or you could even write tasty, appetizing or delicious instead, something really pleasant to the sense of taste. But you will see it very often meaning healthy food, good tasting food that has something more than good taste going for it.",
        "price": 11,
        "name": "Lidia Lynn",
        "company": "ENTHAZE",
        "email": "lidialynn@enthaze.com",
        "phone": "+1 (884) 471-2849"
      },
      {
        "id": "5fc19eb1a7d4dcd0c2f73efc",
        "title": "Breakfast sandwich",
        "category": "breakfast",
        "picture": "https://i.ibb.co/rwG6xNG/breakfast5.png",
        "shortDecription": "How we dream about our future",
        "details": "Toothsome, strictly used, refers to edible and pleasant food, or you could even write tasty, appetizing or delicious instead, something really pleasant to the sense of taste. But you will see it very often meaning healthy food, good tasting food that has something more than good taste going for it.",
        "price": 14,
        "name": "Frank Cantrell",
        "company": "DARWINIUM",
        "email": "frankcantrell@darwinium.com",
        "phone": "+1 (854) 437-3947"
      },
      {
        "id": "5fc19eef752cb56bcb1bfdc0",
        "title": "Fried Chicken Bento",
        "category": "breakfast",
        "picture": "https://i.ibb.co/TqbGNs5/breakfast6.png",
        "shortDecription": "How we dream about our future",
        "details": "Toothsome, strictly used, refers to edible and pleasant food, or you could even write tasty, appetizing or delicious instead, something really pleasant to the sense of taste. But you will see it very often meaning healthy food, good tasting food that has something more than good taste going for it.",
        "price": 14,
        "name": "Brigitte Richmond",
        "company": "VISUALIX",
        "email": "brigitterichmond@visualix.com",
        "phone": "+1 (862) 475-3868"
      },
      {
        "id": "5fc19eef020222b6efd3e99e",
        "title": "French fries with cheese",
        "category": "dinner",
        "picture": "https://i.ibb.co/hHN3J0m/dinner1.png",
        "shortDecription": "How we dream about our future",
        "details": "Toothsome, strictly used, refers to edible and pleasant food, or you could even write tasty, appetizing or delicious instead, something really pleasant to the sense of taste. But you will see it very often meaning healthy food, good tasting food that has something more than good taste going for it.",
        "price": 11,
        "name": "Willis Raymond",
        "company": "APEXIA",
        "email": "willisraymond@apexia.com",
        "phone": "+1 (898) 492-2482"
      },
      {
        "id": "5fc19eef368f5a03719017e6",
        "title": "Lemony Salmon",
        "category": "dinner",
        "picture": "https://i.ibb.co/0qnSq9P/dinner2.png",
        "shortDecription": "How we dream about our future",
        "details": "Toothsome, strictly used, refers to edible and pleasant food, or you could even write tasty, appetizing or delicious instead, something really pleasant to the sense of taste. But you will see it very often meaning healthy food, good tasting food that has something more than good taste going for it.",
        "price": 15,
        "name": "Mcdaniel Trujillo",
        "company": "VICON",
        "email": "mcdanieltrujillo@vicon.com",
        "phone": "+1 (884) 528-2522"
      },
      {
        "id": "5fc19eefa1b5b9373b751eb7",
        "title": "Pork Tenderiain",
        "category": "dinner",
        "picture": "https://i.ibb.co/qkjHrK6/dinner3.png",
        "shortDecription": "How we dream about our future",
        "details": "Toothsome, strictly used, refers to edible and pleasant food, or you could even write tasty, appetizing or delicious instead, something really pleasant to the sense of taste. But you will see it very often meaning healthy food, good tasting food that has something more than good taste going for it.",
        "price": 11,
        "name": "Walsh Barnett",
        "company": "COMTENT",
        "email": "walshbarnett@comtent.com",
        "phone": "+1 (832) 500-2982"
      },
      {
        "id": "5fc19eeff6736419ebce53a5",
        "title": "Salmon with Grapefruits",
        "category": "dinner",
        "picture": "https://i.ibb.co/mFtgPbh/dinner4.png",
        "shortDecription": "How we dream about our future",
        "details": "Toothsome, strictly used, refers to edible and pleasant food, or you could even write tasty, appetizing or delicious instead, something really pleasant to the sense of taste. But you will see it very often meaning healthy food, good tasting food that has something more than good taste going for it.",
        "price": 11,
        "name": "Torres House",
        "company": "EXOPLODE",
        "email": "torreshouse@exoplode.com",
        "phone": "+1 (982) 575-3528"
      },
      {
        "id": "5fc19eef8bc4e3eb85baae2b",
        "title": "Curlic Butter baked salmon",
        "category": "dinner",
        "picture": "https://i.ibb.co/fCT3NtB/dinner5.png",
        "shortDecription": "How we dream about our future",
        "details": "Toothsome, strictly used, refers to edible and pleasant food, or you could even write tasty, appetizing or delicious instead, something really pleasant to the sense of taste. But you will see it very often meaning healthy food, good tasting food that has something more than good taste going for it.",
        "price": 11,
        "name": "Marylou Mcclain",
        "company": "AFFLUEX",
        "email": "maryloumcclain@affluex.com",
        "phone": "+1 (861) 469-3141"
      },
      {
        "id": "5fc19eef8bc4e3eb5baae2b",
        "title": "Baked Chicken",
        "category": "dinner",
        "picture": "https://i.ibb.co/N7Bphv2/dinner6.png",
        "shortDecription": "How we dream about our future",
        "details": "Toothsome, strictly used, refers to edible and pleasant food, or you could even write tasty, appetizing or delicious instead, something really pleasant to the sense of taste. But you will see it very often meaning healthy food, good tasting food that has something more than good taste going for it.",
        "price": 11,
        "name": "Marylou Mcclain",
        "company": "AFFLUEX",
        "email": "maryloumcclain@affluex.com",
        "phone": "+1 (861) 469-3141"
      },
  ]
  export default foods;